version: '3.7'
services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: gooff
      MONGO_INITDB_ROOT_PASSWORD: gooff
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
  web:
    image: node:12.13.1-alpine
    environment:
      - NODE_ENV=production
      - WS_URL="http://web:3000"
      - DB_HOST=database
      - MONGO_INITDB_DATABASE=chat
      - MONGO_INITDB_ROOT_USERNAME=gooff
      - MONGO_INITDB_ROOT_PASSWORD=gooff
    volumes:
      - ./:/app/
    working_dir: /app
    ports:
      - 3000:3000
      - 8000:8000
    command: /bin/sh -c "npm install && exec node ./server/index.js"
    restart: always

